image:
  repository: ghcr.io/naavre/naavre-jupyterlab-dev
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - host: naavre-dev.minikube.test

singleuser:
  baseUrl: /jupyterlab-standalone
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    JUPYTERHUB_USER: 'user'
    VLAB_SLUG: "n-a-a-vre"
    OAUTH_ACCESS_TOKEN: ""
    OAUTH_REFRESH_TOKEN: ""
    NAAVRE_ALLOWED_DOMAINS: "naavre-dev.minikube.test"
