ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: naavre-dev.minikube.test
      paths:
        - path: /NaaVRE-catalogue-service/
          pathType: Prefix

conf:
  base_path: /NaaVRE-catalogue-service
  oidc_configuration_url: https://naavre-dev.minikube.test/auth/realms/vre/.well-known/openid-configuration
  verify_ssl: "false"
  dev_mode: "true"
  django:
    secret_key: fake-secret-key
    superuser_username: admin
    superuser_password: admin

global:
  security:
    allowInsecureImages: true

postgresql:
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  metrics:
    image:
      repository: bitnamilegacy/postgres-exporter