ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: naavre-dev.minikube.test
      paths:
        - path: /NaaVRE-containerizer-service(/|$)(.*)
          pathType: ImplementationSpecific

conf:
  rootPath: /NaaVRE-containerizer-service
  virtual_labs_configuration:
    rawJson: |
      {
        "vl_configurations": [
          {
            "name": "test-virtual-lab-1",
            "base_image_tags_url": "https://github.com/QCDIS/NaaVRE-flavors/releases/latest/download/base_image_tags.json",
            "module_mapping_url": "https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json",
            "cell_github_url": "<set in ./helm-values-local.yaml>",
            "cell_github_token": "<set in ./helm-values-local.yaml>",
            "registry_url": "<set in ./helm-values-local.yaml>"
          }
        ]
      }

env:
  DEBUG: "true"
  VERIFY_SSL: "false"
  OIDC_CONFIGURATION_URL: "https://naavre-dev.minikube.test/auth/realms/vre/.well-known/openid-configuration"
  CONFIG_FILE_URL: "/configuration.json"

livenessProbe:
  httpGet:
    path: /NaaVRE-containerizer-service/docs
    port: http
readinessProbe:
  httpGet:
    path: /NaaVRE-containerizer-service/docs
    port: http
