apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupyterlab-standalone.fullname" . }}
data:
  {{- range $key, $value := .Values.singleuser.extraEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end}}
